### ISSUE TITLE
References to bitstamp

### ISSUE THREAD

**Issue by akhodakivskiy** [bitfinexcom/api_docs#15]
Here and there in the documentation you can find references to Bitstamp, example is on the screenshot below. What does Bitfinex have to do with Bitstamp?

![screenshot from 2015-12-02 18 57 25](https://cloud.githubusercontent.com/assets/145806/11550642/91d7776e-9926-11e5-8f06-50f77a8ecdcf.png)

**Comment by slacknation** [comment]
long time ago they've had bitstamp orders in their exchange but that function has been removed. agree doc should be updated to remove bitstamp

**Comment by joshuarossi** [comment]
hmmm, well...the docs are a representation of the API...what I think you mean is that the API should be updated so that it doesn't have references to Bitstamp (which would then necessitate the updating of the docs)

I'm not sure, I think the docs should be as accurate as possible and should directly reflect the API (picture a program auto generating the docs), so I think that even though you can't actually use that field, it is still a part of the API (and a necessary part of a request)

We are also working on a v2 of the REST API that will be updated so it is much more modern
