### ISSUE TITLE
amount 0 for the same price was sent in book update for websocket

### ISSUE THREAD

**Issue by slacknation** [bitfinexcom/api_docs#8]
e.g.
```
[8,	264.38,	1,	-0.01904707]
[8,	264.38,	0,	0]
after a few updates with other prices
[8,	264.38,	0,	0]
```

**Comment by joshuarossi** [comment]
same as the issue above, i can send an ask with the same price as a bid...right now it is ambiguous about which order you should remove, that is what our next update will address. 

for example, I can have a bid on the book 
```json
[250,1,5]
```
someone sends in an ask at price 250
```json
[250, 1, -1]
```

that ask matches a bid higher than 250 (say the price is 260), that means that the "order" at 250 has been completely filled and needs to be removed.
```json
[250, 0, 0]
```

The original BID at 250 is still there, we wanted to alert you that the ASK at 250 is no longer on the book, but since those two look the same, it is ambiguous...this is the issue that we are addressing
