### ISSUE TITLE
out of sequence/dropped updates for orderbook in websocket

### ISSUE THREAD

**Issue by slacknation** [bitfinexcom/api_docs#9]
e.g.
```
channel	price	count	amount
8	265	1	-5.21
8	265.18	1	-5.16
8	265.27	1	-5.01
8	265.09	2	-9.32
8	264.51	2	27.93259955
8	263.92	0	0
8	263.61	1	5.28
8	263.92	1	12.5
8	263.63	0	0
8	263.61	1	5.28
8	264.51	3	28.17259955
8	263.61	2	5.78
8	264.51	2	27.93259955
8	263.61	1	5.28
8	264.51	3	28.17259955
8	265.34	1	0.581		(bid>ask) there are a few asks in the top few rows that are lower than this bid
8	264.79	1	-8.1818		(bid>ask) this ask is lower than the bid above 
8	265.34	0	0			back to valid orderbook
```
would be good if sequence numbers can be added or a push feed with top 20 bid/ask.

**Comment by joshuarossi** [comment]
thanks for the comments, I think we are rolling out something to address this.
What is happening is, you CAN place an order that crosses the book, we alert you that someone has done that. Of course, when it crosses, it triggers an execution (some people use this instead of market orders), when it fills, it is "removed" from the book, and we then alert you to its removal...technically it never even rested on the book because it matched the first order it encountered, but an order was received and that is why the websocket is forwarding that along. 

We will update the docs when we have the new implementation in place.
